# Nombre de la aplicación
spring.application.name=DeustoCraiAPP

# Apuntamos a la base de datos (deustocrai_db)
spring.datasource.url=jdbc:mysql://localhost:3306/deustocrai_db?serverTimezone=UTC

spring.datasource.username=spq
spring.datasource.password=spq

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jackson.serialization.write-dates-as-timestamps=false