# Nombre de la aplicaci√≥n
spring.application.name=DeustoCraiAPP

# Apuntamos a la base de datos (deustocrai_db)
spring.datasource.url=jdbc:mysql://localhost:3306/deustocrai_db?serverTimezone=UTC

spring.datasource.username=spq
spring.datasource.password=spq

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# --- EMAIL CONFIGURATION ---
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=TU_CORREO_DEUSTO@gmail.com
spring.mail.password=TU_CONTRASE—A_DE_APLICACION
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.jackson.serialization.write-dates-as-timestamps=false
